### ISSUE TITLE
Crash when click on timeline and no debugger is selected

### ISSUE THREAD

**Issue by citronneur** [airbus-cert/ttddbg#2]
When I clicked on the timeline shortcut and no debugger is selected, IDA crashed

**Comment by simsor** [comment]
Can you give me more information about this? I was not able to reproduce the issue.

- Were you using a "fresh" database (i.e. did you have positions already saved in the timeline?)
- By "no debugger is selected", do you mean the dropdown list is on "No debugger" and you are not currently debugging?

On my side, when clicking on the Timeline button while "No debugger" is selected, nothing happens
