### ISSUE TITLE
IDA crash

### ISSUE THREAD

**Issue by HongThatCong** [airbus-cert/ttddbg#9]
IDA will crash when debugger selected not ttddbg
1. Menu Debugger - Switch debugger....
2. In "Select a debugger form...", select a debugger, not ttddbg
3. Run, debug...
4. Click on any button of ttddbg toolbar, IDA will crash
Tks

**Comment by simsor** [comment]
Thanks for the bug report. This has been fixed in 3dd6f38d62199ed4a1745b582057d7c3e1e52e51 by hiding the buttons when "ttddbg" is not selected.

We will soon issue a new release containing this fix.
